### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by jaychoubaby** [picosh/official-blog#1]
remote_key: ${{ secrets.PICO_PRIVATE_KEY }} Is PICO_PRIVATE_KEY the API token? I set it up, but I'm still getting errors.

**Comment by jaychoubaby** [comment]
Error loading key "(stdin)": error in libcrypto
Warning: Permanently added 'prose.sh' (ED25519) to the list of known hosts.
back@prose.sh: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code [12](https://github.com/jaychoubaby/back-s-blog/actions/runs/10157812290/job/28088974406#step:4:13)) at io.c(231) [sender=3.2.7]

**Comment by jaychoubaby** [comment]
I tried setting my computer's private key, and surprisingly it worked. I find this incredible. I think it would be more reasonable to use an API token instead.

**Comment by neurosnap** [comment]
Hi! Because uploading files relies on ssh we need to use an SSH keypair. We could figure out how to let users send an API token as a password but how is that a better solution?

**Comment by jaychoubaby** [comment]
Most software systems typically use an API key for some non-interactive operations, so when I first used it, I naturally filled in the API key. I have now completed the workflow with an SSH private key, and it is running normally. There is no better way, I just followed the habits of most systems. In the end, I am still very grateful for the creation of pico.sh, I really like it very much.

**Comment by neurosnap** [comment]
Great! Pico supports adding multiple keys so we recommend creating a separate SSH key for CI/CD and using that.

**Comment by jaychoubaby** [comment]
Okay, received, thank you very much.
